name: Packaging

on:
  push:
    branches: [ packaging ]
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: install requirements
        run: sudo apt-get update && sudo apt-get install softhsm2 gnutls-bin libengine-pkcs11-openssl python3-dev gcc-x86-64-linux-gnu && python -m pip install --upgrade pip && python -m pip install --upgrade pip-tools

      - name: prep
        run: sudo mkdir -p /var/www/html

      - name: chown
        run: sudo chown `id -u`:`id -g` /var/www/html

      - name: Copy files
        run: cp -r * /var/www/html

      - name: Create env
        run: cd /var/www/html; make venv

      - name: Create archive
        run: tar -zcvf ../harrie14_venv_${{ env.RELEASE_VERSION }}.tar.gz -C /var/www/html/ .venv

      - name: Create release
        run:  tar -cvzf ../harrie14_${{ env.RELEASE_VERSION }}.tar.gz --exclude .git* .

      - name: Upload tar
        uses: actions/upload-artifact@v1
        with:
          name: harrie14_${{ env.RELEASE_VERSION }}
          path: ../harrie14_${{ env.RELEASE_VERSION }}.tar.gz

      - name: Upload venv tar
        uses: actions/upload-artifact@v1
        with:
          name: harrie14_venv_${{ env.RELEASE_VERSION }}
          path: ../harrie14_venv_${{ env.RELEASE_VERSION }}.tar.gz

