name: Create RDO Packages

on:
  push:
    branches: [ packaging ]
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: prep
        run: sudo mkdir -p /var/www/html

      - name: chown
        run: sudo chown `id -u`:`id -g` /var/www/html

      - name: Copy files
        run: cp -r * /var/www/html

      - name: Create env
        run: python3 -m venv /var/www/html/.venv

      - name: pip3 install
        run: cd /var/www/html; source .venv/bin/activate; pip install -U pip; pip install -r requirements.txt

      - name: Create archive
        run: tar -zcvf ../harrie14_venv_${{ env.RELEASE_VERSION }}.tar.gz -C /var/www/html/ .venv

      - name: Create release
        run:  tar -cvzf ../harrie14_${{ env.RELEASE_VERSION }}.tar.gz --exclude .git* .

      - name: Upload tar
        uses: actions/upload-artifact@v1
        with:
          name: harrie14_${{ env.RELEASE_VERSION }}
          path: ../harrie14_${{ env.RELEASE_VERSION }}.tar.gz

      - name: Upload venv tar
        uses: actions/upload-artifact@v1
        with:
          name: harrie14_venv_${{ env.RELEASE_VERSION }}
          path: ../harrie14_venv_${{ env.RELEASE_VERSION }}.tar.gz

